### ISSUE TITLE
Game crashes when I place framed panel

### ISSUE THREAD

**Issue by ElijahLionCub2366** [LoremVIpsum/OpenSimpleFrames#32] opened 2023-12-20 14:07 UTC
I played on 1.20.1 and got the latest version of Open Simple Frames. I played on the latest version of Fabric. Sometimes when I place a framed panel, the game crashes.

**Comment by solonovamax** [comment] 2023-12-23 23:02
This is a duplicate of #20

**Closed as completed** 2024-01-29 12:31 UTC
