### ISSUE TITLE
Crash on place pannel facing down

### ISSUE THREAD

**Issue by Vaerys-Dawn** [LoremVIpsum/OpenSimpleFrames#28] opened 2023-11-22 00:41 UTC
### What happened:  
Game crashes when placing framed pannel on the ground  
  
### What should happen:  
Pannel is placed down  
  
### Steps to reproduce:  
* give yourself a framed pannel  
* look at the ground  
* click  

### Error Log:  

```
[11:35:04] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{simpleframes:framed_panel}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130) ~[client-intermediary.jar:?]
	at com.loremv.simpleframes.blocks.FramePanelBlock.method_9605(FramePanelBlock.java:24) ~[OpenSimpleFrames-1.1.0.jar:?]
	at net.minecraft.class_1747.method_7707(class_1747.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41934(class_636.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41933(class_636.java:324) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1802) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]```

**Comment by LoremVIpsum** [comment] 2023-11-24 14:38
yup its not meant to do that, which version of the game is this? ill fix it as soon as i get time

**Comment by Slowman111** [comment] 2023-12-17 16:11
> yup its not meant to do that, which version of the game is this? ill fix it as soon as i get time

I have the same issue as well with 1.20.1 Fabric version (OpenSimpleFrames  v1.1.0) downloaded from Modrinth)
Thanks.

**Comment by Slowman111** [comment] 2023-12-17 16:33
and the world will shut down when the panel is facing down or facing up

**Comment by solonovamax** [comment] 2023-12-23 23:02
This is a duplicate of #20

**Closed as completed** 2024-01-29 12:31 UTC
